export const URLS = {
    sign_in: 'api/auth/sign-in',
    translations_list: '/api/language/get-all',
    translations_edit: '/api/language/create-edit',
    constants_get_all: '/api/constants/get-all',
    constants_edit: '/api/constants/edit',
    users_get_all: "/api/users/get-all",
    users_block: "/api/users/block",
    users_master: "/api/users/edit/master",
    prizes_list: "/api/prizes/get-all",
    prize_edit: "/api/prizes/edit",
    prize_delete: "/api/prizes/delete",
    prize_add: "/api/prizes/add",
    order_list: "/api/order/get-all",
    file_upload: "/api/images/upload",
};
